### ISSUE TITLE
Add CI

### ISSUE THREAD

**Issue by libremente** [italia/guida-sviluppo-gestione-software-libero#12]
As already mentioned by @bfabio in #9, it could be nice to have an automated way to check for language issues, especially in PRs. 

As such, I believe we should discuss about a possible CI system to use.
This is what comes to my mind now:

1. Check for broken links (internal and external). This is an RST repo, I'm not sure there's a quick way to do it. However, it could be even nicer to have it in the Docs Italia build system. 
2. Run commitlint to check conventional commits compliancy. 
3. Check for language issues, like typos and so on.

@bfabio probably all those points are easily handled with GH Actions, WDYT?

**Comment by bfabio** [comment]
@libremente agreed

Regarding the second point, I'm not a big fan of conventional commits in general and even less so with non-code repos: everything ends up being `fix` and maybe `chore`, but I'm pretty much bike shedding.

**Comment by astagi** [comment]
@libremente @bfabio actions are already running in the CI pipeline. 

@bfabio to mitigate bikeshedding effect and keep homogeneity between commits, I relaxed linting on commits: scope is now optional.

**Comment by libremente** [comment]
Ok I guess we can close this, thanks @astagi
