### ISSUE TITLE
Use `version: "3.5"` in `docker-compose.yml` 

### ISSUE THREAD

**Issue by libremente** [italia/guida-sviluppo-gestione-software-libero#27]
@astagi I'd use `version: "3.5"` in `docker-compose.yml` for us old Debian users :sweat_smile:

_Originally posted by @bfabio in https://github.com/italia/guida-sviluppo-gestione-software-libero/issues/26#issuecomment-819387841_

**Comment by astagi** [comment]
@libremente I made a commit inside that branch

**Comment by astagi** [comment]
This has been fixed, closing...
