### ISSUE TITLE
Stupidi refusi

### ISSUE THREAD

**Issue by adenatale** [italia/guida-sviluppo-gestione-software-libero#34]
Richieste di miglioramento (Feature request)
I Maintainer non sono tenuti a dare attuazione alle richieste di miglioramento o di nuove funzionalità, ma l **_e_** possono valutare insieme ai Project Leader. In ogni caso è bene lasciare aperte le feature request, purché ritenute compatibili con la roadmap del progetto, in modo che si possano raccogliere ulteriori commenti ed essere implementat **_e_** da contributori.

**_Gestione delle issue_**
Il processo di gestione di una issue da parte di un maintainer si articola solitamente in più passaggi:

(ho usato bold+italic per evidenziare il testo, spero sia chiaro)

**Comment by libremente** [comment]
Buongiorno @adenatale, grazie molte! Purtroppo ci sono sfuggiti nella fase di conversione verso l'RST, procediamo subito alla correzione. 
Ancora grazie 🙏
