### ISSUE TITLE
Migliorie sulla Guida allo sviluppo e gestione di software libero

### ISSUE THREAD

**Issue by valerio-bozzolan** [italia/guida-sviluppo-gestione-software-libero#39]
In seguito un articolo che contiene alcuni spunti per migliorare la Guida allo sviluppo e gestione di software libero:

https://www.agendadigitale.eu/cittadinanza-digitale/manuale-duso-del-software-libero-nella-pa-ecco-perche-e-un-freno-alladozione/

A parte i toni dell'articolo su cui non sono completamente in linea, ci sono argomentazioni utili da prendere in esame e su questo ringrazio l'autrice. Tento di riportarle qui:

## Riassunto delle questioni da poter risolvere

* [x] **Indice**: è presente una voce "Per le responsabili politiche e i responsabili politici" che probabilmente è stata introdotta per evitare problemi di genere femminile/maschile però poi il capitolo successivo è "Per gli amministratori pubblici" al maschile e forse in altre parti del testo. Da rivedere un attimo. Personalmente suggerirei "Per chi ha responsabilità politiche"
* [x] **Linguaggio e definizioni**: sarebbe ottimale introdurre un glossario ad inizio del testo per definire certi termini ed evitare che le definizioni siano date più volte all'interno del testo o con sinonimi meno consolidati
    * [x] sarebbe ottimale definire "software libero" ed evitare che le definizioni siano date più volte all'interno del testo o con vari termini meno consolidati (software libero / FLOSS / open source / codice aperto / Open Source / _open source_ etc.).
    * [x] sarebbe ottimale definire l'acronimo "CAD" (Codice dell’amministrazione digitale)
        * [x] attenzione a non chiamarla legge ma decreto legislativo altrimenti le persone potrebbero cercare "L. 82/2005" e non trovare ciò che uscirebbe cercando "D.Lgs 82/2005"
    * [x] sarebbe ottimale definire "licenza libera" evitando (o definendo) gli altri termini simili in uso (licenza aperta / ...)
    * [x] sarebbe ottimale evitare le occorrenze di "enhancement" nel testo o "bug fix" o chiarirle nel glossario etc.
    * [x] sarebbe ottimale definire "software proprietario". Nota personale: in questa definizione può essere utile chiarire che non basta che un pezzo sia libero per chiamarlo libero.
         * [x] Nel "software proprietario" sarebbe forse opportuno includere anche i "servizi non erogabili con software libero" affinchè servizi come "Google Documents" non siano una ambigua scappatoia.
* [x] Nella sezione "A cosa serve questa guida" si legge «Lo scopo di questa guida è quello di supportare concretamente e operativamente le Pubbliche Amministrazioni italiane a districarsi in un contesto nuovo e potenzialmente complesso». Sebbene sia vero che queste questioni siano nuove e complesse per certe persone in certe PA, è vero però che il CAD è stato scritto circa 17 anni fa e di software libero in molte PA ce n'è anche da più anni. Si suggerisce di adottare una frase che non sminuisca questo contesto storico.
* [x] Negli obiettivi si parla di «attrarre nuovi sviluppatori grazie agli ecosistemi aperti» ma la persona che legge il documento potrebbe non avere idea di cosa sia un "ecosistema aperto". Valutare un'altra frase.
* [x] Nella Introduzione si parla di «le migliori tecniche per sviluppare software in un ambiente aperto» ma «ambiente aperto» è un ambiguo al momento. Valutare altro, ad esempio anche solo «le migliori tecniche per sviluppare software libero».
* [x] Nel capitolo "I vantaggi dell’open source" (sotto "Per le responsabili politiche e i responsabili politici") ci sono alcune parti che hanno particolari criticità e necessitano di revisione, fra cui:
    * [x] «_Le politiche pubbliche, definite democraticamente, sono codificate in norme, ovvero un“codice legale”. Questo codice, precursore dei codici «informatici» viene oggi spesso tradotto in algoritmi e codice software ed eseguito da macchine che interpretano il volere del decisore e lo rendono un’azione concreta._» (?)
    * [x] «_I cittadini e gli attori della società civile hanno bisogno che il software sia trasparente e responsabile e che sia quindi progettato e come un’ infrastruttura civica essenziale che rispetti i loro diritti._» (chiarire il pensiero, in particolare forse non è il software ad essere "responsabile" -?- e chiarire il pensiero di fondo dietro a "progettato come un' infrastruttura civica")
* [x] sotto "per gli amministratori pubblici"
    * [x] in "I vantaggi del modello open source": «_L’open source offre un modello di sviluppo migliore rispetto al tradizionale approvvigionamento di software_» - ci sono molti vantaggi del software libero però qui si sta confrontando un modello di sviluppo con un "approvvigionamento di software" e il pensiero non è chiaro.
    * [x] in "I vantaggi del modello open source": «_i fornitori delle organizzazioni pubbliche possono includere l’open source nelle loro offerte per contratti._» - è possibile chiarire meglio “offerte per contratti”
    * [x] in "Norme per l’acquisizione di software per la Pubblica Amministrazione": «_Nel caso in cui la PA decida di acquisire software in licenza o di svilupparne uno nuovo [...] deve motivare tale scelta attraverso la redazione di una valutazione comparativa scritta._» - questa frase potrebbe essere disambiguata meglio, siccome anche il software libero è sotto una licenza. Forse si può rielaborare con "decida di acquisire o sviluppare software proprietario" (con opportuni termini nel glossario).
* [x] nella sezione "I requisiti del software pubblico" revisionare questa parte che ha un pensiero di fondo non chiaro: «_Il software pubblico deve quindi essere: [...] responsabile, nel senso di accountable;_» (il pensiero di fondo si può esprimere meglio, siccome il termine _accountable_ significa “responsabilità nel rendere conto” e forse non è quello che si voleva dire)
* [x] TBD (sto scrivendo)

-----

Altre questioni leggermente correlate:

* [x] Nel README sarebbe utile non dare per scontato che il lettore sappia cosa sia una "issue". Per esempio: «È possibile aprire segnalazioni o richieste qui: [a capo] LINK» etc. - stessa cosa per "pull request", esempio: «Per le persone che desiderano un percorso più collaborativo potete cliccare su "Fork", fare delle modifiche e proporre una "Pull request".» etc. magari con un link ad una guida come [questa](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork)
* [x] Nella parte della licenza potrebbe essere opportuno aggiungere una riga "Copyright (C)  2022 - rispettivi contributori" con un link alla cronologia o [qui](https://github.com/italia/guida-sviluppo-gestione-software-libero/graphs/contributors), a meno che ogni contributore non abbia firmato una cessione dei diritti alla presidenza del consiglio dei ministri

**Comment by ruphy** [comment]
> Nella sezione "A cosa serve questa guida" si legge «Lo scopo di questa guida è quello di supportare concretamente e operativamente le Pubbliche Amministrazioni italiane a districarsi in un contesto nuovo e potenzialmente complesso». Sebbene sia vero che queste questioni siano nuove e complesse per certe persone in certe PA, è vero però che il CAD è stato scritto circa 17 anni fa e di software libero in molte PA ce n'è anche da più anni. Si suggerisce di adottare una frase che non sminuisca questo contesto storico.

Il contesto nuovo è quello introdotto dalle LG del 2019, che è molto diverso dal precedente modello di riuso. Chiarito nel testo

>  attenzione a non chiamarla legge ma decreto legislativo altrimenti le persone potrebbero cercare "L. 82/2005" e non trovare ciò che uscirebbe cercando "D.Lgs 82/2005"

La definizione "L. 82/2005" non la ho trovata da nessuna parte, ho solo trovato "così come richiede la legge" e frasi simili. @valerio-bozzolan ti riferisci a una sezione particolare? Magari mi sono perso qualcosa

**Comment by valerio-bozzolan** [comment]
> La definizione "L. 82/2005" non la ho trovata da nessuna parte, ho solo trovato "così come richiede la legge" e frasi simili. 
> @ruphy

Credo sia questo il paragrafo:

> imposti dalla legge di economicità e di efficienza, tutela degli investimenti, riuso e neutralità tecnologica (art. 68 del CAD).

Da qui:

https://docs.italia.it/italia/developers-italia/guida-sviluppo-gestione-software-libero/it/stabile/introduzione.html?highlight=legge

**Comment by valerio-bozzolan** [comment]
OK. Grazie ancora per quello che state facendo!

**Comment by bfabio** [comment]
@valerio-bozzolan anche gli ultimi due task dovrebbero essere risolti con #57 e #58 :rocket:
