### ISSUE TITLE
Check for grammar errors on PRs

### ISSUE THREAD

**Issue by bfabio** [italia/guida-sviluppo-gestione-software-libero#9]
It would be nice to check for grammar errors on PRs, fe. using this action: https://github.com/reviewdog/action-languagetool

It would be even nicer if we could integrate custom rules from https://github.com/italia/writing-toolkit!

**Comment by libremente** [comment]
Very true, thanks for raising this issue @bfabio.
I'd go one step at a time.
a) Typos and stuff: 
1. Let me first run aspell locally and see what I can fix in the current version.
2. Let's explore a CI for this repo, I'll open a dedicated issue for this.

b) Custom ruleset:
1. Definitely needed, there is already a project working on this, I'll be able to get back to you with a roadmap in the next few weeks.

Thanks!

**Comment by astagi** [comment]
@libremente @bfabio `action-languagetool` is already running in the CI pipeline with the appropriate settings. If it's ok for you please close this issue.

**Comment by bfabio** [comment]
Great, thanks!

@astagi @libremente Maybe we can open another issue for the custom ruleset item?

**Comment by astagi** [comment]
Yes, "custom ruleset" should be a separated issue marked as enhancement
